### ISSUE TITLE
Front - R&D Lib pour les Tiles

### ISSUE THREAD

**Issue by Ganarok** [Ganarok/fichesetchips#104]
Il faut faire une recherche quant à la lib' qu'on va utiliser pour la gestion des tiles dans le Front.

On avait parlé de Canvas déjà. A voir son intégration avec Vue, et plus particulièrement avec Nuxt. Il y a peut être un plugin Nuxt Canvas déjà existant.

**Comment by manon-violeau** [comment]
+ lib pour animation 3d du lancer de dés (tout type de dé 20, 12, 10...)

**Comment by Ganarok** [comment]
> * lib pour animation 3d du lancer de dés (tout type de dé 20, 12, 10...)

On avait grave parlé du classique Three.JS !
A voir
