### ISSUE TITLE
Retour sur la version -1 du site web

### ISSUE THREAD

**Issue by manon-violeau** [Ganarok/fichesetchips#160]
route / : 
- boutons se connecter et s'inscrire non fonctionnels 
- texte en français et en anglais 
- la petite flèche en bas à droite pour remonter, elle devrait pas etre en position absolute pour s'afficher tout le temps ? 
- Y a pas un scroll un peu plus smooth ? 
- Possible d'allumer les boutons se connecter & s'inscrire quand on passe la souris dessus ?

route /login : 
- pas possible de revenir sur l'index 
- formulaire mdp en clair (idem inscription)

Il est où le glossaire / tuto MJ ?

**Comment by zayfix** [comment]
C'est tout cassé sur mobile

**Comment by manon-violeau** [comment]
on peut pas faire une transition index => login plus smooth ? Genre un slide ?

**Comment by mathieuarthur** [comment]
il n'y as pas le visuel pointer quand on survol le lien : pas encore inscrit ou mot de passe oublié

**Comment by manon-violeau** [comment]
- scroll pas user friendly
- modale register => page /register

**Comment by Galadows** [comment]
Problème de logique / agencement des pages mais pour le moment, pas vraiment de "page" inscription,
c'est une modal sur la page de login

**Comment by manon-violeau** [comment]
footer page de contact
