### ISSUE TITLE
Table users

### ISSUE THREAD

**Issue by manon-violeau** [Ganarok/fichesetchips#171]
<b style="font-weight:normal;" id="docs-internal-guid-ec7511d6-7fff-ca89-5ce9-1b8511045655"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User&lt;Entity&gt;</span></h3><br /><div dir="ltr" style="margin-left:0pt;" align="left">

name | type
-- | --
id | UUID
username | string
email | string
password | string
avatar | string
role | [0 : “USER”, 1 : “ADMIN”, 2 : “SUPERADMIN”]
preference_id | UUID
created_at | datetime
updated_at | datetime
last_connection | datetime

</div></b>

**Comment by zayfix** [comment]
Partiellement fait avec e078e9e7ea3ff1566be2033a5cae79a04b5ba947, manque les timestamp et last_connection.

**Comment by zayfix** [comment]
Bueno avec 314091f355ea3c09349541c85773ccade9f5b6d1
