### ISSUE TITLE
Table Préférences

### ISSUE THREAD

**Issue by manon-violeau** [Ganarok/fichesetchips#175]
<b style="font-weight:normal;" id="docs-internal-guid-8b2e2956-7fff-c107-5d50-5ab425a2e1c5"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Preference&lt;Entity&gt;</span></h3><br /><div dir="ltr" style="margin-left:0pt;" align="left">

name | type
-- | --
id | UUID
theme | ligh, dark
language | french, english

</div></b>

**Comment by zayfix** [comment]
Fait avec e078e9e7ea3ff1566be2033a5cae79a04b5ba947 puis fix avec 6db1a67f1b44b7eaa5efc31ce5e7beeec7944b47
