### ISSUE TITLE
Tables Badges et BadgesUsers

### ISSUE THREAD

**Issue by manon-violeau** [Ganarok/fichesetchips#180]
<b style="font-weight:normal;" id="docs-internal-guid-9ee0b873-7fff-fdc1-350d-3ff607775d93"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Badge&lt;Entity&gt;</span></h3><br /><div dir="ltr" style="margin-left:0pt;" align="left">

name | type
-- | --
id | UUID
name | string
image | string
description | text

</div></b>

<b style="font-weight:normal;" id="docs-internal-guid-063858fc-7fff-6fd1-5915-58369b771e0b"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">BadgeUser&lt;PivotTable&gt;</span></h3><br /><div dir="ltr" style="margin-left:0pt;" align="left">

name | type
-- | --
id | UUID
user_id | UUID
badge_id | UUID
created_at | datetime

</div></b>

**Comment by zayfix** [comment]
Bueno 8489ffa842b611b960543675f5c9a10ad1dd25fd
