### ISSUE TITLE
Table Friends

### ISSUE THREAD

**Issue by manon-violeau** [Ganarok/fichesetchips#182]
<b style="font-weight:normal;" id="docs-internal-guid-061e4e48-7fff-bb2e-0e07-b0d88be20351"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Friends&lt;PivotTable&gt;</span></h3><br /><div dir="ltr" style="margin-left:0pt;" align="left">

name | type
-- | --
id | UUID
user_ask_id | UUID
user_answer_id | UUID
nbGames | integer
created_at | datetime

</div></b>

**Comment by zayfix** [comment]
Finito 016c370bcbc06f38610df809e404146b5ab14f79
