### ISSUE TITLE
Front - Créer la page Characters

### ISSUE THREAD

**Issue by Ganarok** [Ganarok/fichesetchips#313]
Il faudrait intégrer la maquette "Mes personnages".

Cette page permettrait d'afficher plusieurs Cartes de personnage. Ainsi, si on clique sur un personnage, on est re-route vers la page de détails d'un personnage (à savoir user/characters/:id)

Il faut aussi pouvoir gérer le cas où l'on a pas créé de personnage, ce qui affiche une option qui redirige sur la page de création d'un personnage (user/characters/create)

**Comment by eVillesseche** [comment]
Après discutions, "Mes personnages" seras component qui seras implémenter dans le profil.
